apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
spec:
  selector:
    matchLabels:
      app: neo4j
  replicas: 1
  serviceName: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: jazinty/neo4j-grandstack
          imagePullPolicy: Always
          ports:
            - containerPort: 7374
              name: browser
            - containerPort: 7587
              name: bolt
          env:
          - name: NEO4J_apoc_import_file_enabled
            value: "true"
          - name: NEO4J_apoc_export_file_enabled
            value: "true"
          - name: NEO4J_dbms_shell_enabled
            value: "true"
          - name: NEO4J_dbms_memory_pagecache_size
            value: "1G"
          - name: NEO4J_dbms_memory_heap_max__size
            value: "1G"
          - name: NEO4J_dbms_connector_bolt_listen__address
            value: ":7587"
          - name: NEO4J_dbms_connector_http_listen__address
            value: ":7374 "
          volumeMounts:
          - name: data
            mountPath: "/data"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "2Gi"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: api-data
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: api
        image: jazinty/api-grandstack
        command: ["npm", "run", "seedDb"]
      restartPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: jazinty/api-grandstack
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: jazinty/ui-grandstack
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
spec:
  selector:
    app: neo4j
  ports:
    - port: 7374
      targetPort: 7374
      name: browser
    - port: 7587
      targetPort: 7587
      name: bolt
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
  - port: 4000
    targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  selector:
    app: ui
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ui
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - hekovnik.grandstack.k8.si
      secretName: grandstack-ui-tls
  rules:
    - host: hekovnik.grandstack.k8.si
      http:
        paths:
          - path: /
            backend:
              serviceName: ui
              servicePort: 3000
          - path: /graphql
            backend:
              serviceName: api
              servicePort: 4000
---
  
